@startuml

"Ciudadano" as ciu
usecase "Tomar huellas" as tom
usecase "Registrar entrada" as regen
ciu -- regen
regen <.. tom : <<extend>>
"Ciudadano extranjero" as extra
extra -- tom
extra --|> ciu

"Usuario" as usuar
:Administrador: as Admin
usecase "Iniciar sesion" as inise
usecase "Recuperar contraseña" as reccontra
usecase "Modificar contraseña" as modcontr
usecase "Cerrar sesion" as cerra
usecase "Registro usuario" as reusua
usecase "Instalar programa" as insp
usuar -- inise
usuar -- reccontra
usuar -- modcontr
usuar -- cerra
Admin -- reusua
Admin -- insp
Admin --|> usuar

actor "new Actor" as nA
usecase "identificarse" as identifi
usecase "Pagar" as Paga
usecase "Elegir mensajero" as Em
usecase "Confirmar" as Con
usecase "Pagar con tarjeta" as Pgt
usecase "Registrarse" as Regis
usecase "Pagar con transferencia" as Ptra
nA -- identifi
nA -- Paga
nA -- Em
nA -- Con
identifi <.. Regis : <<extend>>
Paga <|-- Pgt
Paga <|-- Ptra


actor "Cliente" as clped
usecase "Meter dinero" as Md
usecase "Pedir azucar" as az
usecase "Pedir Producto" as pp
usecase "Cancelar" as cancel
usecase "Devolver dinero" as Devd
clped -- Md
clped -- az
clped -- pp
clped -- cancel
pp ..> Devd : <<include>>
cancel ..> Devd : <<include>>


actor "Cliente" as clvu
actor "Clilente VIP" as vip
clvu <|-- vip
usecase "Reservar vuelo" as rv
usecase "Elegir asientos" as asie
vip --> asie
clvu --> rv

usecase "Pagar" as pag
usecase "Pagar con tarjeta" as pagt
usecase "Pagar en efectivo" as pagoe
 pag <|-- pagt
pag <|-- pagoe

usecase "Acceder" as acc
usecase "Registrarse" as reg
(acc) <.. (reg) : <<extend>>


left to right direction
actor "Cliente" as cl1
usecase "Confirmar pedido" as cp
usecase "Cancelar pedido" as cap
usecase "Devolver cambio" as dc
cl1 -- cp
cl1 -- cap
(cp) ..> (dc) : <<include>>
(cap) ..> (dc) : <<include>>

left to right direction
actor "Cliente" as cl
actor "Restaurante" as re
rectangle  {
  usecase "Mostrar menú" as UC1
  usecase "Pedir comida" as UC2

}
usecase "Entregar comida" as UC3
cl -- UC1
cl -- UC2
re -- UC3
re -- UC1

 :cliente: -- (Mostrar menú)
 Usecase uc1 as "Mostrar menú.."
actor "Cliente" as ctl
@enduml