@startuml

actor "Cliente" as clvu
actor "Clilente VIP" as vip
clvu <|-- vip
usecase "Reservar vuelo" as rv
usecase "Elegir asientos" as asie
vip --> asie
clvu --> rv

usecase "Pagar" as pag
usecase "Pagar con tarjeta" as pagt
usecase "Pagar en efectivo" as pagoe
 pag <|-- pagt
pag <|-- pagoe

usecase "Acceder" as acc
usecase "Registrarse" as reg
(acc) <.. (reg) : <<extend>>


left to right direction
actor "Cliente" as cl1
usecase "Confirmar pedido" as cp
usecase "Cancelar pedido" as cap
usecase "Devolver cambio" as dc
cl1 -- cp
cl1 -- cap
(cp) ..> (dc) : <<include>>
(cap) ..> (dc) : <<include>>

left to right direction
actor "Cliente" as cl
actor "Restaurante" as re
rectangle  {
  usecase "Mostrar menú" as UC1
  usecase "Pedir comida" as UC2

}
usecase "Entregar comida" as UC3
cl -- UC1
cl -- UC2
re -- UC3
re -- UC1

 :cliente: -- (Mostrar menú)
 Usecase uc1 as "Mostrar menú.."
actor "Cliente" as ctl
@enduml